# render.yml
services:
  - type: web
    name: conversation-summary-server
    runtime: node
    region: oregon  # or choose another region
    plan: starter   # free tier
    autoDeploy: true
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 5000
      - key: SPREADSHEET_ID
        sync: false  # Set in Render dashboard
    scaling:
      minInstances: 1
      maxInstances: 10
      targetMemoryPercent: 70